<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20251215160113 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE business (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(100) NOT NULL, coords VARCHAR(50) NOT NULL, zone_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_8D36E389F2C3FAB ON business (zone_id)');
        $this->addSql('CREATE TABLE zone (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(100) NOT NULL, center_coords VARCHAR(50) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('ALTER TABLE business ADD CONSTRAINT FK_8D36E389F2C3FAB FOREIGN KEY (zone_id) REFERENCES zone (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE business DROP CONSTRAINT FK_8D36E389F2C3FAB');
        $this->addSql('DROP TABLE business');
        $this->addSql('DROP TABLE zone');
    }
}
